---
title: "Homework 2"
author: "Mingee Choi"
date: 10/05/2022
output: github_document
---

Load Packages

```{r setup, message=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
```

# Problem 2

To import and clean Mr. Trash Wheel and Professor Trash Wheel datasets:

```{r}
mr_trash_wheel_df=
  read_excel("./data/trash.xlsx", sheet=1, range = "A2:N549")%>%
  janitor::clean_names()%>%
  drop_na(data=., dumpster)%>%
  mutate(sports_balls=as.integer(sports_balls))

professor_trash_wheel_df=
  read_excel("./data/trash.xlsx", sheet=2, range = "A2:M96")%>%
  janitor::clean_names()%>%
  drop_na(data=., dumpster)%>%
  mutate(year=as.character(year))
```

To combine two datasets together:

```{r}
trash_df=
   left_join(mr_trash_wheel_df, professor_trash_wheel_df, by="dumpster" , copy=TRUE)%>%
    mutate (trash_wheel_type= case_when(dumpster <95 ~"professor",
                                        dumpster >95 ~"mr")
    )%>%
  relocate(dumpster, trash_wheel_type)
```



# Problem 3




